# -- test/testdata/infer/autocorrect_block_return.rb --
# typed: true

extend T::Sig

sig {params(blk: T.proc.params(xs: T::Array[Integer]).returns(Integer)).void}
def example(&blk)
  yield [0]
end

example(&T.must(:first)) # error: Expected `Integer` but found `T.nilable(Integer)` for block result type

example {|x| T.must(x.first)} # error: Expected `Integer` but found `T.nilable(Integer)` for block result type
# ------------------------------
